In [2]:
import numpy as np

### Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [3]:
x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[3 5]
[2 5]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


### Write a NumPy program to create a 3x3 identity matrix.

In [4]:
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height. 

Sample Output:

Original array:

[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
(b'Pit', 5, 40.11)]

Sort by height

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
(b'Nail', 6, 52.5 )]

In [5]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height')) 

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


### Write a NumPy program to get the indices of the sorted elements of a given array. 

Expected Output:

Original array:

[1023 5202 6230 1671 1682 5241 4532]

Indices of the sorted elements of a given array:

[0 3 4 6 1 5 2]

In [6]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print("Original array:")
print(student_id)
i = np.argsort(student_id)
print("Indices of the sorted elements of a given array:")
print(i)

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


### Write a NumPy program to sort an given array by the nth column.

Original array:

[[1 5 0]

[3 2 5]

[8 7 6]]

Sort the said array by the nth column:

[[3 2 5]

[1 5 0]

[8 7 6]]

In [7]:
print("Original array:\n")
nums = np.random.randint(0,10,(3,3))
print(nums)
print("\nSort the said array by the nth column: ")
print(nums[nums[:,1].argsort()])

Original array:

[[1 3 0]
 [0 9 6]
 [5 8 0]]

Sort the said array by the nth column: 
[[1 3 0]
 [5 8 0]
 [0 9 6]]


### Write a NumPy program to get the dates of yesterday, today and tomorrow.

Sample Output:

Yestraday:  2022-04-11

Today:  2022-04-12

Tomorrow:  2022-04-13

In [8]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2022-04-11
Today:  2022-04-12
Tomorrow:  2022-04-13


### Write a NumPy program to find the number of weekdays in March 2017.
Note: "busday" default of Monday through Friday being valid days.

Sample Output:

Number of weekdays in March 2022:
23

In [10]:
print("Number of weekdays in March 2022:")
print(np.busday_count('2022-03', '2022-04'))

Number of weekdays in March 2022:
23


### Write a NumPy program to convert numpy datetime64 to Timestamp.

Sample output:

Current date:
2022-04-12 12:28:12.526553

Timestamp:
1649766492.526553

UTC from Timestamp:
2022-04-12 12:28:12.526553

In [11]:
from datetime import datetime
dt = datetime.utcnow()
print("Current date:")
print(dt)
dt64 = np.datetime64(dt)
ts = (dt64 - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
print("Timestamp:")
print(ts)
print("UTC from Timestamp:")
print(datetime.utcfromtimestamp(ts))

Current date:
2022-04-12 12:28:12.526553
Timestamp:
1649766492.526553
UTC from Timestamp:
2022-04-12 12:28:12.526553


d:\VSPROJECTS\jupyterenv\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  


### Write a NumPy program to get true division of the element-wise array inputs.

Expected Output:

Original array:
[0 1 2 3 4 5 6 7 8 9]

Division of the array inputs, element-wise:
[ 0. 0.33333333 0.66666667 1. 1.33333333 1.6666666
7 2. 2.33333333 2.66666667 3. ]

In [12]:
x = np.arange(10)
print("Original array:")
print(x)
print("Division of the array inputs, element-wise:")
print(np.true_divide(x, 3))

Original array:
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


### Write a NumPy program to get the largest integer smaller or equal to the division of the inputs. 

Expected Output:

Original array:
[1.0, 2.0, 3.0, 4.0]

Largest integer smaller or equal to the division of the inputs:
[ 0. 1. 2. 2.]

In [13]:
x = [1., 2., 3., 4.]
print("Original array:")
print(x)
print("Largest integer smaller or equal to the division of the inputs:")
print(np.floor_divide(x, 1.5))

Original array:
[1.0, 2.0, 3.0, 4.0]
Largest integer smaller or equal to the division of the inputs:
[0. 1. 2. 2.]
