### Write a NumPy program to generate five random numbers from the normal distribution.

Expected Output:
[-0.43262625 -1.10836787 1.80791413 0.69287463 -0.53742101]

In [ ]:
#try your code here

### Write a NumPy program to generate six random integers between 10 and 30.

Expected Output:
[20 28 27 17 28 29]

In [ ]:
#try your code here

### Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

input: 

x = np.array([3, 5])

y = np.array([2, 5])

In [ ]:
#try your code here

### Write a NumPy program to create a 3x3 identity matrix.

In [ ]:
#try your code here

### Write a NumPy program to get the powers of an array values element-wise. 

Note: First array elements raised to powers from second array

Expected Output:

Original array
[0 1 2 3 4 5 6]

First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [ ]:
#try your code here

### Write a NumPy program to repeat all the elements three times of a given array of string 

Expected Output:

Original Array:
['Python' 'PHP' 'Java' 'C++']

New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']

In [ ]:
#try your code here

### Write a NumPy program to remove the leading whitespaces of all the elements of a given array. 

Sample Output:

Original Array:
[' python exercises ' ,' PHP ' ,' java ' ,' C++']

Remove the leading whitespaces : ['python exercises ', 'PHP ' ,'java ' ,'C++']

In [ ]:
#try your code here

### Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height. 

Sample Output:

Original array:

[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
(b'Pit', 5, 40.11)]

Sort by height

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
(b'Nail', 6, 52.5 )]

In [ ]:
#try your code here

### Write a NumPy program to get the indices of the sorted elements of a given array. 

Expected Output:

Original array:

[1023 5202 6230 1671 1682 5241 4532]

Indices of the sorted elements of a given array:

[0 3 4 6 1 5 2]

In [ ]:
#try your code here

### Write a NumPy program to sort an given array by the nth column.

Original array:

[[1 5 0]

[3 2 5]

[8 7 6]]

Sort the said array by the nth column:

[[3 2 5]

[1 5 0]

[8 7 6]]

In [ ]:
#try your code here

### Write a NumPy program to get the dates of yesterday, today and tomorrow.

Sample Output:

Yestraday:  2022-04-11

Today:  2022-04-12

Tomorrow:  2022-04-13

In [ ]:
#try your code here

### Write a NumPy program to find the number of weekdays in March 2017.
Note: "busday" default of Monday through Friday being valid days.

Sample Output:

Number of weekdays in March 2022:
23

In [ ]:
#try your code here

### Write a NumPy program to convert numpy datetime64 to Timestamp.

Sample output:

Current date:
2022-04-12 12:28:12.526553

Timestamp:
1649766492.526553

UTC from Timestamp:
2022-04-12 12:28:12.526553

In [ ]:
#try your code here

### Write a NumPy program to get true division of the element-wise array inputs.

Expected Output:

Original array:
[0 1 2 3 4 5 6 7 8 9]

Division of the array inputs, element-wise:
[ 0. 0.33333333 0.66666667 1. 1.33333333 1.6666666
7 2. 2.33333333 2.66666667 3. ]

In [ ]:
#try your code here

### Write a NumPy program to get the largest integer smaller or equal to the division of the inputs. 

Expected Output:

Original array:
[1.0, 2.0, 3.0, 4.0]

Largest integer smaller or equal to the division of the inputs:
[ 0. 1. 2. 2.]

In [ ]:
#try your code here

### Write a NumPy program to sort the specified number of elements from beginning of a given array. 

Sample output:

Original array:
[0.39536213 0.11779404 0.32612381 0.16327394 0.98837963 0.25510787 0.01398678 0.15188239 0.12057667 0.67278699]

Sorted first 5 elements:
[0.01398678 0.11779404 0.12057667 0.15188239 0.16327394 0.25510787 0.39536213 0.98837963 0.32612381 0.67278699]

In [ ]:
#try your code here