# **Numpy Broadcasting**

In [8]:
import numpy as np

## **Broadcasting Rules:**

### Broadcasting two arrays together follow these rules:
* *If the arrays don’t have the same rank then prepend the shape of the lower rank array with 1s until both shapes have the same length.*
* *The two arrays are compatible in a dimension if they have the same size in the dimension or if one of the arrays has size 1 in that dimension.*
* *The arrays can be broadcast together iff they are compatible with all dimensions.*
* *After broadcasting, each array behaves as if it had shape equal to the element-wise maximum of shapes of the two input arrays.*
* *In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.*

### Single Dimension array 

In [9]:
a = np.array([10, 11, 17]) # 1x3 Dimension array
print(a)
b = 3 
print(b)
 
# Broadcasting happened because of miss match in array Dimension.
c = a + b
print(c)

[10 11 17]
3
[13 14 20]


### Two Dimensional Array 

In [10]:
a = np.array([[10, 11, 17],[6,29,13]]) # 2x3 Dimension array
print(a)
b = 4 
print(b)
 
# Broadcasting happened because of miss match in array Dimension.
c = a + b
print(c)

[[10 11 17]
 [ 6 29 13]]
4
[[14 15 21]
 [10 33 17]]


In [11]:
 
v = np.array([12, 24, 36]) 
w = np.array([45, 55])   
 
# To compute an outer product we first
# reshape v to a column vector of shape 3x1
# then broadcast it against w to yield an output
# of shape 3x2 which is the outer product of v and w
print(np.reshape(v, (3, 1)) * w)

[[ 540  660]
 [1080 1320]
 [1620 1980]]


In [12]:
x = np.array([[12, 22, 33], [45, 55, 66]])
 
# x has shape  2x3 and v has shape (3, )
# so they broadcast to 2x3,
print(x + v)

[[ 24  46  69]
 [ 57  79 102]]


In [13]:
# Add a vector to each column of a matrix X has
# shape 2x3 and w has shape (2, ) If we transpose X
# then it has shape 3x2 and can be broadcast against w
# to yield a result of shape 3x2.
 
# Transposing this yields the final result
# of shape  2x3 which is the matrix.
print((x.T + w).T)

[[ 57  67  78]
 [100 110 121]]


In [14]:
# Another solution is to reshape w to be a column
# vector of shape 2X1 we can then broadcast it
# directly against X to produce the same output.
print(x + np.reshape(w, (2, 1)))

[[ 57  67  78]
 [100 110 121]]


In [15]:
# Multiply a matrix by a constant, X has shape  2x3.
# Numpy treats scalars as arrays of shape();
# these can be broadcast together to shape 2x3.
print(x * 2)

[[ 24  44  66]
 [ 90 110 132]]
