# Part 3


## NumPy

In [ ]:
import numpy as np # import numpy and give it the short form ('nickname') np

<b>From Wikipedia:
    
NumPy (pronounced /ˈnʌmpaɪ/ (NUM-py) or sometimes /ˈnʌmpi/ (NUM-pee)) is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. The ancestor of NumPy, Numeric, was originally created by Jim Hugunin with contributions from several other developers. In 2005, Travis Oliphant created NumPy by incorporating features of the competing Numarray into Numeric, with extensive modifications. NumPy is open-source software and has many contributors.</b>

<a href = "https://en.wikipedia.org/wiki/NumPy">Full article here</a>

Some important **Numpy** features:
<ul>
<li>ndarray: fast and space-efficient multidimensional array with vectorized arithmetic and sophisticated broadcasting</li>
<li>Standard vectorized math</li>
<li>Reading / writing arrays to disk</li>
<li>Memory-mapped file access</li>
<li>Linear algebra, rng, fourier transform</li>
<li>Integration of C, C++, FORTRAN</li>
</ul>

**Creating NumPy arrays**

The function *array()* is commonly used to create numpy ndarrays on the fly from other Python sequence-like objects such as tuples and lists.

In [ ]:
np.array(range(3))

In [ ]:
np.array((1, 2, 3)) # from a tuple

In [ ]:
np.array([1, 2, 3]) # from a list

In [ ]:
type(np.array(range(3)))

Nested lists result in mutlidimensional arrays:

In [ ]:
import random
nestedList = [[random.uniform(0, 9) for x in range(3)] for y in range(4)]
nestedList

[[8.536348291941575, 7.891253521865471, 7.102633827261235],
 [3.535019178626484, 5.375644307938026, 3.7624950708902203],
 [5.202315910294648, 5.316586496061198, 4.295567253931664],
 [2.9787051451413915, 3.1780647001719107, 2.609184108942338]]

In [ ]:
type(nestedList)

list

In [ ]:
myArray = np.array(nestedList)
myArray

array([[8.53634829, 7.89125352, 7.10263383],
       [3.53501918, 5.37564431, 3.76249507],
       [5.20231591, 5.3165865 , 4.29556725],
       [2.97870515, 3.1780647 , 2.60918411]])

**Important attributes of arrays**

In [ ]:
print(myArray.ndim)  # Number of dimensions
print(myArray.shape) # Shape of the ndarray
print(myArray.dtype) # Data type contained in the array

2
(4, 3)
float64


#### Other functions to create arrays

**arange** - this is equivalent to the range function, except returns a one-dimensional array instead of a range object: 

In [ ]:
np.arange(10)

**ones**, **zeros**, **ones_like**, **zeros_like** - to create arrays filled with ones or zeroes with a given shape or with a shape similar to a given object:

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,4))

In [ ]:
np.zeros(4)

In [ ]:
np.zeros((4,3))

We can explicitly specify the data type with which an array should be created:

In [ ]:
newArray = np.array(nestedList, dtype = np.int)
newArray

In [ ]:
newArray = np.array(nestedList, dtype = np.float)
newArray

In [ ]:
newArray = np.array(nestedList, dtype = np.bool) # numbers = 0 are False
newArray

In [ ]:
newArray = np.array(nestedList, dtype = np.unicode) # Unicode strings
newArray

In [ ]:
newArray = np.array(nestedList, dtype = np.object) # arbitrary objects
newArray

## Vectorized math

One of the most powerful and useful features of numpy, especially for data science, is the ability to vectorize mathmatical operations - that is to apply operations to each element of a vector or array simultaneously without needing to use a *for* loop

In [ ]:
myArray

array([[8.53634829, 7.89125352, 7.10263383],
       [3.53501918, 5.37564431, 3.76249507],
       [5.20231591, 5.3165865 , 4.29556725],
       [2.97870515, 3.1780647 , 2.60918411]])

In [ ]:
%%time
myArray + 3

CPU times: user 199 µs, sys: 94 µs, total: 293 µs
Wall time: 313 µs


array([[11.53634829, 10.89125352, 10.10263383],
       [ 6.53501918,  8.37564431,  6.76249507],
       [ 8.20231591,  8.3165865 ,  7.29556725],
       [ 5.97870515,  6.1780647 ,  5.60918411]])

In [ ]:
myArray2 = np.array([[random.uniform(0, 3) for x in range(3)] for y in range(4)]) 
# creating a nested list and then a 2D array in one step
myArray2

array([[2.53433959, 0.34878003, 1.22546269],
       [2.85883185, 0.85258116, 1.80331168],
       [0.05563128, 2.0013303 , 1.38297307],
       [2.74105944, 0.62555095, 0.72315589]])

In [ ]:
myArray + myArray2

array([[11.07068788,  8.24003355,  8.32809652],
       [ 6.39385103,  6.22822547,  5.56580675],
       [ 5.25794719,  7.3179168 ,  5.67854032],
       [ 5.71976459,  3.80361565,  3.33234   ]])

In [ ]:
newArray = myArray.astype(np.int)
newArray

array([[8, 7, 7],
       [3, 5, 3],
       [5, 5, 4],
       [2, 3, 2]])

In [ ]:
newArray * 3

array([[24, 21, 21],
       [ 9, 15,  9],
       [15, 15, 12],
       [ 6,  9,  6]])

In [ ]:
newArray * [1,2,3] 
# Elementwise multiplication on rows
# That is, in each row, the first column is multiplied by 1, the second by 2 and the third by 3

array([[ 8, 14, 21],
       [ 3, 10,  9],
       [ 5, 10, 12],
       [ 2,  6,  6]])

In [ ]:
x = np.array([[1], [2], [3], [4]])
x.shape

(4, 1)

In [ ]:
newArray * [[1], [2], [3], [4]] # Elementwise multiplication on rows

array([[ 8,  7,  7],
       [ 6, 10,  6],
       [15, 15, 12],
       [ 8, 12,  8]])

These types of numpy operations make it very easy and efficient to work with matrices and perform matrix algebra

In [ ]:
np.sqrt(newArray)

In [ ]:
np.log(newArray + 1) # to avoid a log(0) error

array([[2.19722458, 2.07944154, 2.07944154],
       [1.38629436, 1.79175947, 1.38629436],
       [1.79175947, 1.79175947, 1.60943791],
       [1.09861229, 1.38629436, 1.09861229]])

These vectorized functions return an array of the appropriate shape - the same shape as the input array in the examples above.

There are also operations that are applied to an array which return a scalar value, usually the result of some type of aggregation

In [ ]:
np.sum(newArray,axis = 0)

array([18, 20, 16])

In [ ]:
np.max(newArray)

8

In [ ]:
np.mean(newArray)

4.5

#### What we have looked at here is just a small fraction of the operations and functionality available with numpy arrays - we have only looked at some of the features that are most relevant for us.