In [1]:
import numpy as np

### Write a NumPy program to generate five random numbers from the normal distribution.

Expected Output:
[-0.43262625 -1.10836787 1.80791413 0.69287463 -0.53742101]

In [2]:
x = np.random.normal(size=5)
print(x)

[-0.25583327 -0.37829475  0.98649451  0.1050823  -0.57637731]


### Write a NumPy program to generate six random integers between 10 and 30.

Expected Output:
[20 28 27 17 28 29]

In [3]:
x = np.random.randint(low=10, high=30, size=6)
print(x)

[29 14 26 28 24 14]


### Write a NumPy program to get the powers of an array values element-wise. 

Note: First array elements raised to powers from second array

Expected Output:

Original array
[0 1 2 3 4 5 6]

First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [4]:
x = np.arange(7)
print("Original array")
print(x)
print("First array elements raised to powers from second array, element-wise:")
print(np.power(x, 3))

Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[  0   1   8  27  64 125 216]


### Write a NumPy program to repeat all the elements three times of a given array of string 

Expected Output:

Original Array:
['Python' 'PHP' 'Java' 'C++']

New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']

In [5]:
x1 = np.array(['Python', 'PHP', 'Java', 'C++'])
print("Original Array:")
print(x1)
new_array = np.char.multiply(x1, 3)
print("New array:")
print(new_array)

Original Array:
['Python' 'PHP' 'Java' 'C++']
New array:
['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']


### Write a NumPy program to remove the leading whitespaces of all the elements of a given array. 

Sample Output:

Original Array:
[' python exercises ' ,' PHP ' ,' java ' ,' C++']

Remove the leading whitespaces : ['python exercises ', 'PHP ' ,'java ' ,'C++']

In [6]:
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'])
print("Original Array:")
print(x)
stripped = np.char.strip(x)
print("\nRemove the leading and trailing whitespaces: ", stripped)

Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading and trailing whitespaces:  ['python exercises' 'PHP' 'java' 'C++']


### Write a NumPy program to sort the specified number of elements from beginning of a given array. 

Sample output:

Original array:
[0.39536213 0.11779404 0.32612381 0.16327394 0.98837963 0.25510787 0.01398678 0.15188239 0.12057667 0.67278699]

Sorted first 5 elements:
[0.01398678 0.11779404 0.12057667 0.15188239 0.16327394 0.25510787 0.39536213 0.98837963 0.32612381 0.67278699]

In [7]:
nums =  np.random.rand(10)
print("Original array:")
print(nums)
print("\nSorted first 5 elements:")
print(nums[np.argpartition(nums,range(5))])

Original array:
[0.45986405 0.14940237 0.89372843 0.27101933 0.69480827 0.35917612
 0.3317235  0.95523377 0.16574615 0.94411613]

Sorted first 5 elements:
[0.14940237 0.16574615 0.27101933 0.3317235  0.35917612 0.69480827
 0.89372843 0.95523377 0.45986405 0.94411613]
